$ANSIBLE_VAULT;1.1;AES256
66326463363661373235396166323961336663356161633730643366383330313064623261636538
3230626333623033653962633637366566643432646239640a306438623230616336306361623536
32393031366664653430386338323830626364636533353638346362363139356630303830346661
6538383034643930620a333836313830376664333730313835306534313733333366626666313132
63383435316634346534623536373961616462613062373435356165383239643363656663323064
32383363346232386438626534636439633639653538656330303435666133356230306463353339
36616462303962363231323336303966343638353830663065383335313638643036343431616662
30376331376437626565636263636362303961373931616561313331616431646436343864373565
31393530356136386537343633343636346634653266623130626233633535316438613838653436
38663966353234343336323566383137336631636537383261353364363936393934343763373535
66363766323030336238363931326365613761383166636565306638306439636136313063613435
66316333303264373035306465653036653636313566396439643861343765643166383264356163
6561
